[plugin]
repository = "https://github.com/SalvatoreDevelopment/AetherFM.git"
commit = "d75c63b8a50025d376a4a745676d678e9e04c595"
owners = ["SalvatoreDevelopment"]
project_path = ""
changelog = "Initial release: listen to radio in FFXIV! Streams online radio stations in-game with a modern UI. No API key required, no usage limits." 
