[plugin]
repository = "https://github.com/SalvatoreDevelopment/AetherFM.git"
commit = "50b537eafeb2ee4c89093a73bba3d7355c58403e"
owners = ["SalvatoreDevelopment"]
project_path = "."
changelog = """
v1.2.0: IPC gates, Global search, Custom Stations, background playback, robustness.
- Formal IPC call gates (incl. ResumeLast, TogglePlayStop); non-throw policy; ordered events
- Global search (name/tag/language) and Custom Stations (add/list/remove)
- Favorites enhancements (names API), favorites always visible
- More stations: limit=10000, hide broken, clickcount order; wider stream validation (http/https,/stream, mp3/aac)
- Background playback toggle (ON by default): stop on close only if disabled
- Start/Stop synchronization hardened to avoid NAudio races.
"""