[plugin]
repository = "https://github.com/SalvatoreDevelopment/AetherFM.git"
commit = "45b2bd37b69ad10f2f57b7a51a5274bacc05b006"
owners = ["SalvatoreDevelopment"]
project_path = ""
changelog = "Initial release: listen to radio in FFXIV! Streams online radio stations in-game with a modern UI. No API key required, no usage limits." 